# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69e45aa3490175f1c05dfeb86f6bfc080095a25db8f000d0b978392437f3e974d42d85ee91901b6c3aba42c3a828972fe1547531dcaa9f90f6c101aaf6ed57f8

test:
  secret_key_base: f84ca4df26b5ccbc3f02e1d73b85d222c256b15886fb27518cd91d6a814485fa071516b2cbd16c9a853d5730874e1543212a72ccfac813ec1f66144f3d152edf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
